berkmancenter/lumendatabase

- lib/tasks/chillingeffects.rake
Cleaned up some of the types, made csv an arg with default
> csv argument and bug fixes

- doc/api_documentation.mkd
Name "submitter" added.
Field "zip" added.
> Adding missing parameters for entities

- Gemfile.lock
- README.md
- app/models/notice.rb
- app/views/pages/disclaimer.html.erb
- app/views/pages/legal.html.erb
- app/views/shared/_footer.html.erb
- lib/ingestor.rb
- spec/factories.rb
- spec/integration/page_titles_spec.rb
* Pull in a change already in master
* Fix a test broken by that change
* Additional documentation
* Dependency loading order (ingestor + importer)
* Prevent a circular dependency where rake commands (even ones to create tables) fail because of a missing table.
> Sundry Build/Environment Fixes

- lib/tasks/chillingeffects.rake
This change wasn't pulled in from #302 before it was closed. This diff will look a lot better than #302 did so that's probably better in the end.
> Fix a bad git merge (remove code that should have been replaced).

- lib/tasks/chillingeffects.rake
For notices with "url_..." in their subjects.
> Add an information gathering rake task.

- app/models/government_request.rb
- app/models/notice.rb
- app/views/notices/_government_request_form.html.erb
- app/views/notices/_government_request_show.html.erb
- app/views/notices/_government_request_works.html.erb
- config/initializers/rails_admin.rb
- config/locales/en.yml
- spec/factories.rb
> Add GovernmentRequest Notice type.

- app/models/defamation.rb
- app/models/other.rb
- app/models/searchability.rb
Update searchability to allow for "exclusions" to be passed in.
This change requires a search reindex.
> Remove Work#description from Defamation and Other search indexes.

- app/models/work.rb
- spec/lib/ingestor/importer/google_secondary/other_parser_spec.rb
Also update matching URLs already present in the DB.
> Update Work "before save" code so it preserves URL redactions.

- app/models/redacts_notices.rb
- lib/ingestor/importer/google_secondary/redacted_content.rb
- spec/lib/ingestor/importer/google_secondary/other_parser_spec.rb
- spec/support/example_files/secondary_other_redaction_notice_source.html
Handle hyphens differently.
Tweak regex generation slightly for non-English characters.
Decode URLs before redacting them.
> Update Entity Name Redaction to account for some edge cases.

- app/controllers/home_controller.rb
Also rescue Twitter errors that prevent the home page from loading:
Twitter::Error::Forbidden:
Unable to verify your credentials
P.S.
Looks like we think alike. Nearly identical solutions to the same problem!
> Address some deprecation warnings.

- app/assets/javascripts/faceted_search_form.js.coffee
- app/helpers/notices/search_helper.rb
- app/models/notice.rb
- app/models/unspecified_term_filter.rb
- app/views/notices/search/_term_filter.html.erb
- spec/models/unspecified_term_filter_spec.rb
Add some test coverage for the new class.
> Tweak facets' behavior to handle missing + empty-string facets.

- lib/ingestor/legacy/attribute_mapper.rb
- spec/integration/imports_existing_data_as_csv_spec.rb
- spec/integration/page_titles_spec.rb
- spec/integration/reviewable_notice_spec.rb
- spec/integration/submit_notice_via_web_spec.rb
- spec/integration/user_authorizes_spec.rb
- spec/integration/user_submits_typed_notices_spec.rb
- spec/lib/ingestor/importer/google_secondary/other_parser_spec.rb
- spec/lib/ingestor/legacy/attribute_mapper_spec.rb
- spec/lib/ingestor/legacy/error_handler_spec.rb
- spec/models/work_spec.rb
- spec/support/example_files/blogger_dmca_source.txt
- spec/views/home/index.html.erb_spec.rb
Only one failing test left for me and that appears to be an actual bug. Super Admins don't appear to be able to update User email addresses through the RailsAdmin UI.
> Fix a large set of broken tests.

- app/models/work.rb
- spec/lib/ingestor/legacy/attribute_mapper_spec.rb
- spec/models/work_spec.rb
Fix a bug highlighted by the tests.
Fix the setup for two AttributeMapperSpec tests.
> Rework some WorkSpec tests to cover what they are supposed to.

- spec/controllers/notices_controller_spec.rb
I finally fixed that awful FactoryGirl issue I was having. I think it wasn't working because of where I was trying to place the test in the notices_controller_spec.rb file.
> Test to see if researchers get original URLs when they request via API.

- config/initializers/rack-attack.rb
Passenger filters underscore HTTP headers per
https://github.com/phusion/passenger/issues/1707 so we moved to headers
with X and dashes.
> Fix Rack Attack Configuration for Passenger

- spec/integration/submit_notice_via_api_spec.rb
Commit 806dea4e52bd6a30d75f1b829fe77ace3eabcb7b introduced a new header
style and this commit updates the integration spec to work with it.
> Update test with new header style

- Gemfile.lock
- app/models/notice.rb
- app/models/searchability.rb
- spec/integration/api_notice_search_spec.rb
* Adds the ability to search by submitters
* Or to select a submitter facet in results
* Updates relevant test
> Add submitter facet to search

- app/assets/javascripts/faceted_search_form.js.coffee
* Checks if checkbox is checked before creating hidden field with all the search terms.
> Fixes passing all serach terms param

- app/models/defamation.rb
* Uses same code as in the other.rb model
> Hide senders in defamation notices sent to Google

- app/models/risk_trigger.rb
* This should fix the too many arguments error caused when submitting the DMCA web form
> Fix DMCA web form submission error

- app/models/ability.rb
* Adds ability to create Notices and Blog Entries to the admin role.
> Add ability to admin role

- app/models/risk_trigger.rb
> Change key that risk trigger checks

- app/controllers/home_controller.rb
- app/views/home/index.html.erb
* Fragment cache the latest blog posts to decrease the hits to the database.
> Fragment cache blog posts

- app/assets/javascripts/notices_show.js.coffee
- app/views/notices/show.html.erb
- No longer changes text on supporting documents when they are clicked.
> Stops changing text on supporting documents

- app/assets/stylesheets/rails_admin/custom/theming.scss
- Fixes mistmatched sidebar in Rails Admin UI
- Puts redact labels on their own lines
- Fixes overlapping checkbox from review required
> Fix redact queue UI issues

- app/assets/javascripts/notices_new.js.coffee
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/notices/_forms.scss
Fixes select2 to appropraitely style the submission form so that selections are no longer hidden.
> Fix form input selects

- app/views/pages/privacy.html.erb
Since we do not have a newsletter we are removing this copy about the newsletter to avoid confusion.
> Remove copy related to newsletters

- spec/controllers/home_controller_spec.rb
- Caching feature caused the test doubles to not be equal so had to clear cahce before these tests
> Fixes failing home controller test

- app/views/home/_notice.html.erb
- app/views/home/index.html.erb
This fixes all of the 70 specs. 
This blocked me from completing my GSoC. This fixes the tests I was having problems with. I still would like to contribute and finish what I had planned.
> Fix failing tests.

- app/views/pages/about.html.erb
Reverts berkmancenter/lumendatabase#457
> revert pull to master-legacy

- app/models/notice_search_result.rb
See comment in file for details.
> Suppress spurious warning from test suite

- app/views/notices/submission_disabled.html.erb
- db/seeds.rb
- spec/integration/submit_notice_via_web_spec.rb
- spec/integration/user_submits_typed_notices_spec.rb
This also updates tests to be consistent with the new expectation.
> Update text of submission page

- .travis.yml
- app/controllers/notices_controller.rb
- spec/integration/api_notice_search_spec.rb
- spec/integration/rails_admin_dashboard_spec.rb
- spec/integration/redaction_spec.rb
- spec/integration/submit_notice_via_web_spec.rb
- spec/rails_helper.rb
- spec/support/devise.rb
- spec/support/live_searching.rb
- spec/support/notice_actions.rb
- spec/support/page_objects/notice_submission_on_page.rb
- spec/support/rendered_page.rb
**ON HOLD** - tests that succeed on localhost are failing on Travis; this PR will remain open as I work those out but is not ready for review.
This PR cleans up the test suite by:
* tracking down and remedying intermittent failures
* fixing any tests which were still failing
This should cause the test suite to reliably succeed when invoked via `bundle exec rspec spec/`, as directed in the README.
> Test suite rampage 3

- lib/tasks/chillingeffects.rake
**YES**
Please note that this PR has **special deployment instructions**. To wit:
* remove the chill-prod cron job that runs `Rails.cache.clear` every 20 minutes
* add one that runs `rake chillingeffects:safer_cache_clear` every 20 minutes
Fixes https://cyber.harvard.edu/projectmanagement/issues/14130 .
To understand this fix, it is necessary to understand the following sequence of events, which can happen in the fragment caching process:
* Rails checks for the existence of a cache key.
* If the associated file either does not exist or is expired, it goes to write the file: https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/cache/file_store.rb#L79
* That cache-writing function ensures that the relevant directory exists
* It then calls out to the following …
> Decrease aggressiveness of cache clearing (fixes #14130)

- db/migrate/20180815162606_add_index_to_notices.rb
- db/schema.rb
- doc/release.md
- spec/models/dmca_spec.rb
**YES | NO**
A few sentences describing the overall goals of the pull request's commits.
Why are we making these changes? Is there more work to be done to fully
achieve these goals?
YES | NO
YES | NO
> Hotfix db index

- .rubocop.yml
- README.md
- Rakefile
- app/controllers/home_controller.rb
- app/controllers/notices_controller.rb
- app/middleware/catch_json_parsing_errors.rb
- app/models/reindex_run.rb
- app/views/home/index.html.erb
- app/views/notices/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- lib/tasks/chillingeffects.rake
- spec/config/initializers/rack-attack_spec.rb
- spec/controllers/entities/search_controller_spec.rb
- spec/controllers/home_controller_spec.rb
- spec/integration/submit_notice_via_api_spec.rb
- spec/models/searches_models_spec.rb
- spec/spec_helper.rb
- spec/support/curb_helpers.rb
- spec/support/elasticsearch.rb
- spec/views/home/index.html.erb_spec.rb
**YES**
Mostly linting/style. Massages some syntax around ES test cluster startup/teardown.
I was continuing to investigate test performance and reliability and came across a lot of random crud that seemed worth fixing. Also some of these are style-only changes that arose in the context of work on other branches, that I've pulled out and put here to simplify the review of those branches.
I would like Rubocop to stop yelling at me to the greatest extent reasonably possible.
Also I was poking at test speed, and discovered that running without the integration tests results in pretty good coverage and takes ~56 seconds instead of ~8.5 minutes, so I documented that.
There should not be any visible changes, except to developer happiness.
n/a
NO
NO
> Test suite rampage 5

- config/application.rb
- config/environments/production.rb
- config/environments/staging.rb
- doc/release.md
* Improve release docs from experience releasing a hotfix
* Lint some stuff
**YES**
Various stylistic cleanup that I came across in the context of another PR, but separated out from it for ease of reviewing.
n/a
NO
NO
> Misc cleanup

- config/initializers/elasticsearch.rb
**YES**
Adds a timeout to Elasticsearch requests.
- https://cyber.harvard.edu/projectmanagement/issues/14440
NO
NO
> 14440 es timeout

- ELASTICSEARCH_INDEXING.md
- IMPORTING.md
- README.md
- app/controllers/home_controller.rb
- app/views/home/index.html.erb
- app/views/pages/research.html.erb
- config/environments/production.rb
- config/environments/staging.rb
- config/initializers/devise.rb
- db/seeds/blog_entries.rb
- db/seeds/relevant_questions.rb
- db/seeds/topics.rb
- db/seeds/users.rb
- doc/chill.dia
- doc/release.md
- lib/tasks/chillingeffects.rake
- spec/integration/publish_via_rake_task_spec.rb
- spec/support/example_files/mixed-charset-source.html
- spec/support/example_files/youtube_counterfeit.html
- spec/support/example_files/youtube_trademarkcomplaintd.html
This PR will have __special deployment instructions__; crontabs on enyos, percy, and flutie will need to be edited so to run `rake lumen:*` tasks rather than `rake chillingeffects:*` tasks.
**NO**
This removes references to chillingeffects.org where appropriate. See expanded commit comments for details.
Once upon a time, there was a web site called Chilling Effects....now it's not called that.
- https://cyber.harvard.edu/projectmanagement/issues/15685
NO
NO
> 15685 no chill

- .gitignore
- config/initializers/elasticsearch.rb
- doc/release.md
**YES**
Tidies up some issues found in the 2.1.5 release to flutie.
the computers should go
n/a
NO
NO
> Release 215 hotfixes

- app/controllers/blog_entries_controller.rb
- app/controllers/topics_controller.rb
- app/helpers/blog_entry_helper.rb
- app/helpers/notices_helper.rb
- app/helpers/topics_helper.rb
- app/models/blog_entry.rb
- app/models/searches_models.rb
- app/models/work.rb
- app/views/blog_entries/archive.html.erb
- app/views/notices/search/index.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_head.html.erb
- app/views/shared/_header_search.html.erb
- app/views/shared/_navigation.html.erb
- app/views/shared/_regulation_list.html.erb
- app/views/topics/show.html.erb
- config/environments/test.rb
- config/initializers/cache_helper.rb
- config/initializers/rack-attack.rb
- db/seeds.rb
- spec/controllers/topics_controller_spec.rb
- spec/integration/viewing_topics_spec.rb
- spec/views/topics/show.html.erb_spec.rb
**YES**
I inventoried expensive pages on Skylight for places that caching might help. Pageload times on localhost look improved (the specifics will be different in prod because of the radically different data).
Notably, `notices/_works_urls.html.erb` is slow but caching doesn't actually get at the root of the slow load time there - that's something best addressed through SQL or allocation strategies.
- https://cyber.harvard.edu/projectmanagement/issues/15704
NO
NO
> 15704 fragment caching

- lib/tasks/lumen.rake
**YES**
see commit message
~~I'm going to put the new cron job on flutie now. Half an hour from now, you should not have email.~~
Update: Two hours later, I did not have email.
n/a
NO
NO
> Hotfix cron job

- Gemfile
- Gemfile.lock
**YES**
- https://cyber.harvard.edu/projectmanagement/issues/15871
NO
YES
> Upgrade loofah gem

- config/initializers/rack-attack.rb
**YES**
Updates throttling policy, which was much more permissive than intended.
n/a -- see ganglia instead
NO
NO
> 16359 better throttling

- .gitignore
- config/environments/production.rb
- doc/release.md
- lib/tasks/lumen.rake
**YES**
Removes the public download page for the customer service report recently merged; intstead emails the user.
n/a (conversation with jsd)
NO
NO
> Email user rather than writing HTML page for notification

- app/controllers/token_urls_controller.rb
YES
We don't know why captcha requests fail, this should help debugging.
https://cyber.harvard.edu/projectmanagement/issues/16537
~~- [ ] Stakeholder approval~~
NO
NO
> Temporary logging of recaptcha errors

- Gemfile.lock
- app/controllers/token_urls_controller.rb
YES
We're experiencing issues with verifying the full notice request captcha. Let's update the `recaptcha` gem and see if it helps.
https://cyber.harvard.edu/projectmanagement/issues/16537
~~- [ ] Stakeholder approval~~
NO
YES
> 16537 update recaptcha gem

- config/application.rb
- spec/requests/compressions_spec.rb
**YES**
The HTTP responses that are sent will be compressed if requested
- https://cyber.harvard.edu/projectmanagement/issues/16320
NO
NO
> compress http responses and test

- app/models/infringing_url.rb
- app/models/notice.rb
- spec/models/infringing_url_spec.rb
**YES**
Gets the count of notices and approximate count of infringing URL's
https://cyber.harvard.edu/projectmanagement/issues/16595
https://cyber.harvard.edu/projectmanagement/issues/16596
NO
NO
> Get count of notices and URLs

- .travis.yml
- Gemfile
- Gemfile.lock
- spec/factories.rb
- spec/integration/faceted_notice_search_spec.rb
- spec/integration/notice_search_spec.rb
- spec/models/dmca_spec.rb
- spec/models/factories_spec.rb
- spec/models/notice_submission_initializer_spec.rb
- spec/rails_helper.rb
- spec/support/elasticsearch.rb
- spec/support/factory_bot.rb
- spec/support/factory_girl.rb
- spec/support/fielded_search_notice_generator.rb
There proved to be a lot of breaking changes in this upgrade, so:
* Change all FactoryGirl references to FactoryBot
* Change factories to use procs, not constants (prevents error about
not being able to modify a frozen array)
* Change various builds to creates to force a save so that we can
access id attributes -- it wasn't a problem before but is now
* Deal with FactoryBot being generally more persnickety about instance
validation
But now the tests pass again. Yay!
**YES | NO**
A few sentences describing the overall goals of the pull request's commits.
Why are we making these changes? Is there more work to be done to fully
achieve these goals?
YES | NO
YES | NO
> Update FactoryGirl to FactoryBot

- .travis.yml
- README.md
- lib/tasks/lumen.rake
- spec/config/initializers/rack-attack_spec.rb
- spec/integration/getting_topics_through_api_spec.rb
- spec/tasks/generate_court_order_report_spec.rb
- spec/views/notices/new.html.erb_spec.rb
**YES**
* fixes a bug whereby our last rake task report email didn't send
* makes it possible to have multiple recipients for the email
* adds some token testing
n/a (failed cron job report in email)
NO
NO
> Bugfix rake emails

- app/models/entity.rb
- app/models/notice.rb
- spec/models/dmca_spec.rb
- spec/models/entity_spec.rb
- spec/models/redaction/refill_queue_spec.rb
**YES**
Search for an entity, you should get all the notices in which this entity is involved. Also, a UI filter in a future ticket, would be provided by which you can filter the role in which the user is present.
- https://cyber.harvard.edu/projectmanagement/issues/16599
NO
NO
> Notices by submitters receivers senders [Ready for review]

- config/initializers/rack-attack.rb
- lib/rack-attack/request.rb
- spec/config/initializers/rack-attack_spec.rb
- spec/support/elasticsearch.rb
**YES**
Enforces previously-soft API limits. Makes tests of the throttles actually work.
- https://cyber.harvard.edu/projectmanagement/issues/16943
NO
NO
> 16943 api limits

- lib/rack-attack/request.rb
- spec/lib/rack-attack/request_spec.rb
**YES**
Fixes a stupid bug in the new rack attack code.
n/a (via email)
NO
NO
> Hotfix rack attack

- lib/rack-attack/request.rb
- spec/lib/rack-attack/request_spec.rb
**YES | NO**
A few sentences describing the overall goals of the pull request's commits.
Why are we making these changes? Is there more work to be done to fully
achieve these goals?
YES | NO
YES | NO
> Hotfix rack attack dev

- app/assets/stylesheets/shared/_navigation.scss
- app/views/pages/about.html.erb
- app/views/pages/legal.html.erb
- app/views/pages/privacy.html.erb
- app/views/pages/researchers.html.erb
- app/views/shared/_navigation.html.erb
**YES**
updates text of about, researchers, legal, privacy pages
Look at those pages on the dev server (or just read the diff)
n/a
- ~[ ] Tests~
NO
NO
> Update text for /pages/*

- app/views/pages/about.html.erb
**YES**
Compare text of about page
n/a
- ~[ ] Tests~
NO
NO
> About page text tweaks

- app/controllers/files_controller.rb
- spec/integration/downloading_documents.rb
**YES**
Downloads were broken. This unbreaks them.
Try to download a file against the current master branch. It fails! Oh noes! Then download it using this. It works! Whew.
Run tests against master. They pass, even though downloads are failing. Oh noes! Apply the update in `spec/integration/downloading_documents.rb` to master and run the tests. They fail, as one would hope, given that master is broken! Whew.
n/a
NO
NO
> Fix paperclip

- app/assets/stylesheets/shared/_navigation.scss
**YES**
Fixes bug in search result dropdown display (introduced by changing nav styling to allow for CMS link management).
- https://cyber.harvard.edu/projectmanagement/issues/17181
NO
NO
> Fix display of search results dropdowns

- app/helpers/notices_helper.rb
- app/models/counterfeit.rb
- app/models/notice.rb
- app/views/entities/_address.html.erb
- app/views/entities/_entity.html.erb
- app/views/notices/_counterfeit_form.html.erb
- app/views/notices/_counterfeit_show.html.erb
- app/views/notices/_counterfeit_works.html.erb
- app/views/notices/show.html.erb
- spec/helpers/notices_helper_spec.rb
- spec/integration/user_submits_typed_notices_spec.rb
**YES**
Adds new Notice type.
- https://cyber.harvard.edu/projectmanagement/issues/17214
NO
NO
> 17214 counterfeit notices

- config/locales/en.yml
- spec/factories.rb
- spec/support/matchers/have_words.rb
- spec/views/notices/show.html.erb_spec.rb
**YES**
This should have been part of #604.
NO
NO
> Handle failing tests

- app/controllers/notices_controller.rb
- lib/validates_urls.rb
- spec/controllers/notices_controller_spec.rb
- spec/integration/submit_notice_via_web_spec.rb
- spec/integration/user_submits_typed_notices_spec.rb
- spec/models/infringing_url_spec.rb
- spec/support/notice_actions.rb
**YES**
#606 didn't quite fix all the things; this continues the work.
- https://cyber.harvard.edu/projectmanagement/issues/17224
NO
NO
> More notice submission fixes

- .gitignore
- CHANGELOG.md
- app/helpers/application_helper.rb
- config/application.rb
- config/initializers/comfortable_mexican_sofa.rb
- config/initializers/mini-profiler.rb
- lib/rack-attack/request.rb
- spec/integration/viewing_notices.spec.rb
**YES**
Removes all `blacklist` and `whitelist` references from the repository.
According to many research papers both words can be considered as racist language.
See
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/
or
https://www.pcmag.com/news/uk-cybersecurity-agency-drops-blacklist-and-whitelist-terms-over-racial
or
https://bugs.chromium.org/p/chromium/issues/detail?id=981129#c16.
No changes in the application functionality, just in the code.
No.
NO
NO
> Remove blacklist and whitelist references

- app/models/reindex_run.rb
**YES**
Fixes metadata for ReindexRuns so they can stop spamming  our logs.
- https://cyber.harvard.edu/projectmanagement/issues/16771
- ~[ ] Tests~
- ~[ ] Stakeholder approval~
NO
NO
> 16771 reindex metadata

- app/controllers/notices_controller.rb
**YES**
Improves flash message and fixes redirect behavior after manual submission.
Broke this in a previous PR when I was trying to be helpful, whoops.
Submit a notice through the web form on dev and on this branch. Read the message, look at the page -- you're redirected to a different page that makes more sense.
- https://cyber.harvard.edu/projectmanagement/issues/17263
- ~[ ] Tests~
NO
NO
> Fix notice creation redirection bug

- app/controllers/search_controller.rb
1) We should limit based on the number of results, not the number of
pages, since per_page can be changed.
2) Make the messaging more accurate.
This has also been updated in the API documentation.
**YES**
per above
Set the page? query to something really high on a search and look at the error message.
- https://cyber.harvard.edu/projectmanagement/issues/16197
NO
NO
> Improve communication around deep pagination

- doc/ELASTICSEARCH_INDEXING.md
- doc/release.md
**YES**
Adds documentation around elasticsearch upgrades, so that future ones will be easier.
- https://cyber.harvard.edu/projectmanagement/issues/17209
n/a
NO
NO
> Add documentation for future-us

- app/models/elasticsearch/searchability.rb
**NO**
This can't be deployed until the backing production index is available that matches its mapping.
Sets up some copy_to fields in order to decrease the number of fields in MULTI_MATCH_FIELDS. Also adds a test to ensure that newly created Notices get indexed, and explicitly includes elasticsearch callbacks to make that happen.
Searching across too many fields is slow, but the `_all` field no longer exists. So we need to create our own fields to search in.
NO
NO
> Rewrite search options

- Gemfile
- Gemfile.lock
- app/views/entities/_sender.html.erb
**YES**
Adds a flag emoji next to country
Feature #13509
View Country on a Complaint
- https://cyber.harvard.edu/projectmanagement/issues/13509#change-81766
NO
YES
> 13509 flag thumbnail
