bin/setup
Fixes issue where setup fails if no `tmp` directory exists
=> Create tmp directory during setup

app/views/notices/show.html.erb
until we can reassign non-DMCA notices out of this type, remove the type label from display
=> remove Notice Type display, while DMCA bug exists

doc/api_documentation.mkd
Add GovernmentRequest to the list of allowed types for Notices coming in via the api.
=> 12390 documentation update

app/models/work.rb, app/views/notices/_url_input_group.html.erb, spec/views/notices/new.html.erb_spec.rb
This is the fix for Bug #8341. After implementation the DMCA notice submission form should no longer require that a URL be submitted for the original work.
=> Remove requirement that URL of copyrighted work be included in web form.

app/controllers/notices_controller.rb, app/helpers/notices_helper.rb, app/models/dmca.rb, app/models/notice.rb, config/initializers/inflections.rb, config/locales/en.yml, doc/api_documentation.mkd, lib/ingestor.rb, lib/ingestor/importer/base.rb, lib/ingestor/importer/google_secondary/dmca_parser.rb, lib/ingestor/importer/google_secondary/eb_dmca_parser.rb, lib/tasks/chillingeffects.rake, spec/controllers/notices_controller_spec.rb, spec/integration/imports_existing_data_as_csv_spec.rb, spec/integration/page_titles_spec.rb, spec/integration/submit_notice_via_web_spec.rb, spec/lib/ingestor/importer/google_secondary/dmca_parser_spec.rb, spec/lib/ingestor/importer/google_secondary/eb_dmca_parser_spec.rb, spec/lib/ingestor/importer/google_spec.rb, spec/lib/ingestor/legacy_spec.rb, spec/models/dmca_spec.rb, spec/models/entity_notice_role_spec.rb, spec/models/submit_notice_spec.rb, spec/models/work_spec.rb, spec/support/notice_actions.rb, spec/views/notices/new.html.erb_spec.rb
Include rake tasks to up_dmca_migration and down_dmca_migration.
Care should be taken when deploying this. Database entries with type = 'Dmca' will cause errors like:
> LoadError: Expected <RAILS_ROOT>/app/models/dmca.rb to define Dmca
Run `rake chillingeffects:up_dmca_migration` to do an `UPDATE` command changing 'Dmca' to 'DMCA' in the database. The single `UPDATE` might lock the database for too long on production. But without the 'Dmca' to 'DMCA' change, the server is likely to experience the `LoadError` above whenever any 'Dmca' Notices are returned.
=> Change the Dmca class to DMCA.

db/migrate/20150917014052_add_url_original_to_copyrighted_urls.rb, db/migrate/20150917014352_add_url_original_to_infringing_urls.rb, db/schema.rb, lib/default_url_original.rb
Allows us to bring the site back up faster.
=> Tweak migrations to rename url columns instead of replace them.

.gitignore, app/controllers/original_files_controller.rb, app/models/ability.rb, app/models/file_upload.rb, config/routes.rb, spec/controllers/original_files_controller_spec.rb
I experimented with moving the public/support directory on my local machine and did not encounter any errors. I'm not 100% sure how that will work with a server that has ongoing traffic. Might need to disable access to the site until the directory finishes its move then bring it back up with the code changes in place.
=> Move paperclip storage for FileUploads and guard with a controller.

config/initializers/rails_admin.rb
This should fix the error that we were getting when trying to edit notices in Rails Admin.
=> Rails admin edit error fix

app/models/notice.rb, app/models/searches_models.rb, spec/integration/api_notice_search_spec.rb, spec/models/searches_models_spec.rb
Keeps facet results from leaking hidden, spam, rescinded, or unpublished data.
=> Add visible checks to SearchesModels queries to limit facet results.

db/migrate/20160222192409_add_notes_to_notices.rb, db/schema.rb
This adds a field to the notices model for admins to take notes in.
This field will be visible to everyone that has access to RailsAdmin.
=> Add notes field to notices model

spec/lib/ingestor/importer/google_secondary/other_parser_spec.rb
Commit b8e679845e43c2e474091d6ebd2acb3f0fcca753 redacts the entire Google
quote automatically. This updates the test to reflect this new reality.
=> Update test for redacting all of Google quotes

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/rack-attack.rb, spec/config/initializers/rack-attack_spec.rb
* Updated rack-attack to throttle json requests without a header
* Tests throttling of both API requests and HTTP requests
=> Add tests for rack attack

app/models/risk_trigger.rb
*When submitting a notice via web interface as a logged out user an error would say wrong number of arguments (1 for 0) on the submitter. This fixes that error.
=> Fixes risk trigger no argument error

app/models/redacts_notices.rb, spec/models/redacts_notices_spec.rb
Fixes an edge case where long Turkish phone numbers with spaces in them were not being redacted.
=> Redact Turkish phone numbers with spaces in them

app/models/redacts_notices.rb, spec/models/redacts_notices_spec.rb
* This feature causes the content redactor to not redact stopwords that might be part of a company name or other text portion that it wants to redact.
=> Do not redact stopwords

README.md
Bumped the Ruby version in the README file. Gem install on Ruby 2.1.9 have been successful on me El Capitan. I need to know if my PRs can now be merged. Testing waters.
=> Edit Ruby version in README

lib/tasks/chillingeffects.rake
* Searches for Google and Twitter entities with similar names and assigns them to the original entity.
* Takes Google entities with additional information between brackets and turns them into tags.
=> Add rake tasks to consolidate entities

app/views/rails_admin/application/_redact_everywhere_form.html.erb, lib/rails_admin/config/actions/redact_notice.rb, spec/factories.rb, spec/integration/redaction_queue_spec.rb, spec/rails_admin/config/actions/redact_notice_spec.rb
- Instead of merely redacting the notices that are visible in the redact queue redact all will now redact all notices marked review_required.
=> Change redact all to redact all notices in queue

app/views/notices/show.html.erb
- Leaves notice for subsequent viewers that the document was already requested.
=> Leaves note that original document was requested

lib/tasks/chillingeffects.rake
- Will fix google notices in redact queue so they do not include unneeded text in the body field
- Removes the Google API defamation complaints from the redact queue
=> Add tasks for updating Google notices

app/models/notice.rb
Rails admin was not allowing users to delete an entity notice role. This would cause a problem if an entity was associated in multiple roles for a notice and a user wanted to change the name/assocation for one entity but not the other one. This change allows the admin user to sever the relationship and then create a new entity to make this kind of change.
=> Allow removal of nested entity notice roles

app/views/counter_notices/_form.html.erb
The DMCA counter-notice generator radio buttons were not displaying properly because the simple-form update did not give them the class that styled them that the old version had. This manually gives the labels their class and thus fixes the styling.
=> Fix counter-notice radio buttons

app/models/notice.rb, app/models/searchability.rb, app/views/notices/search/index.html.erb, spec/integration/api_notice_search_spec.rb, spec/support/fielded_search_notice_generator.rb, spec/views/notices/search/index.html.erb_spec.rb
- Since :submitter_country_code did not work for unknown reasons I had to use a workaround to index those
- Lets users search the submitter country codes in advanced search
=> Make submitter country codes searchable

ELASTICSEARCH_INDEXING.md, README.md, db/seeds.rb
The current prod version of elasticsearch is 5.6, not 1.7.6. In
addition, db/seeds.rb was inconsistent with the current version of the
elasticsearch library. These updated instructions reduce yakshaving
for new users setting up a first instance.
=> Fix setup instructions

db/migrate/20180815162606_add_index_to_notices.rb, db/schema.rb
**YES**
Adds an index to `Notice.created_at`.
In Skylight we see that the home page can take an excessively long time to load, and nearly the entirety of this time is spent in SQL (see e.g. https://www.skylight.io/app/applications/utm46ElcSDtw/1534327080/1h27m/endpoints/HomeController%23index?responseType=html).
The SQL query includes an `ORDER_BY` on `Notice.created_at`. This column is not indexed, so it needs to sort on the fly, which is slow.
I did some performance tests on localhost in psql as follows. As you can see, the planning and execution time increase quite markedly as the number of records increases, but the indexed version is dramatically faster.
\c lumen_dev
explain (analyze) SELECT  "notices".* FROM "notices" WHERE "notices"."spam" = false AND "notices"."hidden" = false AND …
=> Add index to Notice.created_at

app/models/notice.rb, app/views/notices/show.html.erb, spec/models/dmca_spec.rb, spec/views/notices/show.html.erb_spec.rb
**YES**
Removes the related FAQs and blogs from Notices - they were very resource-intensive to construct.
If we decide we want some amount of FAQ content to be here, an alternative would be:
* select one random related topic
* pull some of its related content
* cache that template fragment, using the topic ID in the key
That should be more performant than the status quo, but less performant than just removing the feature entirely.
Constructing four inner joins when some of the tables have millions of entries is slow, even if you indexed things.
Compare, e.g., https://lumendatabase.org/notices/1 and http://flutie.law.harvard.edu:8000/notices/300073651 (scroll down).
- https://cyber.harvard.edu/projectmanagement/issues/15224
NO
NO
=> 15224 faq perf

app/models/government_request.rb, spec/controllers/notices_controller_spec.rb, spec/integration/submit_notice_via_web_spec.rb
**YES**
Adds submitter field to Government Request notice type per client request. This is based on master so we can deploy it as a hotfix since the client is eager to see it.
Compare `/notices/new?type=GovernmentRequest` on localhost and prod. 
- https://cyber.harvard.edu/projectmanagement/issues/15439
NO
NO
=> 15439 submitter field

lib/tasks/lumen.rake
We're still getting email every 20 minutes when find has a time of
check/time of use problem with identifying vs deleting empty
directories. Let's just not bother hearing those errors.
This only affects the output of the find command; we'll still get
errors logged if the rake task itself encounters problems.
**YES**
see commit message above
20 minutes after it's deployed, you shouldn't have email from chill-prod.
n/a
NO
NO
=> Suppress irritating find errors

app/controllers/notices_controller.rb, public/404_hidden.html, spec/controllers/notices_controller_spec.rb
Some notices must be hidden due to e.g. ongoing legal proceedings and
it would be misleading to say that they will eventually become
available. Therefore we use a stripped-down 404 message for hidden
notices.
**YES**
see above
see ticket
compare /notices/X for a hidden notice on this branch vs dev
- https://cyber.harvard.edu/projectmanagement/issues/15812
NO
NO
=> Render different message for hidden than unpublished messages

app/models/notice.rb, spec/integration/rails_admin_dashboard_spec.rb, spec/support/page_objects/admin_on_page.rb
**YES**
Deleting notices through the admin interface was failing because the
self.index line threw an exception - possibly a holdover from an older
version of ElasticSearch?
log in as superadmin, go to `/admin/notice`, click the x to delete a notice, confirm on the next page, it should work
Note that you need to have ElasticSearch running and your env configured properly to talk to it - otherwise you'll get a 500.
- https://cyber.harvard.edu/projectmanagement/issues/15852
NO
NO
=> Bugfix Notice deletion

app/assets/javascripts/notices_new.js.coffee, app/assets/stylesheets/notices/_new.scss, app/models/notice_submission_initializer.rb, app/views/notices/form_components/_additional_metadata.html.erb, spec/integration/submit_notice_via_web_spec.rb, spec/support/notice_actions.rb
__YES__
Removes the file category select from the notice web form.
See https://github.com/berkmancenter/lumendatabase/pull/494
* Go to notices/new/type=Whatever
* File category select shouldn't be there
- https://cyber.harvard.edu/projectmanagement/issues/14893
Todo:
- ~~[  ]  Documentation~~
__NO__
__NO__
=> 14893 webform doc type

Gemfile, Gemfile.lock, spec/integration/fielded_notice_search_spec.rb, spec/models/searches_models_spec.rb, spec/rails_helper.rb, spec/support/curb_helpers.rb, spec/support/elasticsearch.rb, spec/support/vcr.rb, spec/support/webmock.rb, spec/vcr/SearchesModels/filters/asks_for_the_filter.yml, spec/vcr/SearchesModels/filters/correctly_configures_facets.yml, spec/vcr/SearchesModels/finds_the_index_name_from_the_model_class.yml, spec/vcr/SearchesModels/returns_an_elasticsearch_search_instance.yml, spec/vcr/SearchesModels/searches/dispatches_to_a_registered_term_search.yml, spec/vcr/SearchesModels/searches/dispatches_with_an_operator.yml
* Add and configure VCR and Webmock
* Upgrade Curb and use Curb::Easy (the other ones, Curb and Curb::Multi,
are not supported by VCR)
* Configure Elasticsearch to work nicely with VCR
* Add VCR recordings for the SearchModels model
**YES**
Adding VCR so that non-integration tests don't depend on Elasticsearch.
Run specs, it won't call Elasticsearch and will use VCR recordings instead in the SearchModels model spec.
https://cyber.harvard.edu/projectmanagement/issues/15706
NO
YES
=> Add VCR to specs

.gitignore, app/models/counternotice.rb, app/models/court_order.rb, app/models/data_protection.rb, app/models/defamation.rb, app/models/dmca.rb, app/models/government_request.rb, app/models/law_enforcement_request.rb, app/models/notice.rb, app/models/other.rb, app/models/private_information.rb, app/models/trademark.rb, spec/integration/user_submits_typed_notices_spec.rb, spec/models/court_order_spec.rb, spec/models/defamation_spec.rb, spec/models/dmca_spec.rb, spec/models/government_request_spec.rb, spec/models/law_enforcement_request_spec.rb, spec/models/other_spec.rb, spec/models/private_information_spec.rb, spec/models/trademark_spec.rb, spec/spec_helper.rb
**YES**
Adds 'submitter' as a default on all `Notice` subclasses.
Look at the forms for Notice subclasses on localhost vs production - all Notice types should include a 
submitter metadata section on localhost, even though not all of them do on prod.
- https://cyber.harvard.edu/projectmanagement/issues/15439
NO
NO
=> 15439 more submitters

.gitignore, config/initializers/rails_admin.rb, spec/integration/user_authorizes_spec.rb, spec/support/page_object.rb
**YES**
I've talked to Adam about his usage of the admin page but I will want to put it on flutie before we merge - Peter, please tell me when I can do that without stepping on your tests.
The rails admin is exceptionally slow on prod. Skylight indicates that repeated database queries are a culprit; I can't trace down exactly where those queries are happening, but a lot of googling suggests they're in rendering nested forms, particularly in harvesting the data needed for associated entities represented in nested forms - we just have to traverse too much of our database. These changes reduce the amount of data we pull in to render `/admin/notice/X/edit`, and as a result on localhost this page loads about 6.5 times faster (I expect the difference will be even larger on prod where the …
=> 15702 railsadmin edit perf

spec/integration/fielded_notice_search_spec.rb
**YES **
It tries to make the integration tests a bit more stable.
- https://cyber.harvard.edu/projectmanagement/issues/15901
NO
NO
=> Get rid of sleeps in integration specs of advanced search

spec/integration/submit_notice_via_api_spec.rb, spec/integration/submit_notice_via_web_spec.rb, spec/models/dmca_spec.rb
YES
Adds some tests to make sure the entity type gets set properly on notice submission.
- https://cyber.harvard.edu/projectmanagement/issues/15786
NO
NO
=> Make sure entity type gets set properly on notice submission

app/controllers/notices_controller.rb, app/models/ability.rb, app/models/instance_redactor.rb, app/models/notice.rb, app/models/redacts_notices.rb, app/models/reindex_run.rb, app/models/work.rb, app/views/pages/researchers.html.erb, doc/release.md, lib/rails_admin/config/actions/redact_notice.rb, lib/tasks/lumen.rake, spec/integration/notice_search_spec.rb, spec/models/dmca_spec.rb, spec/models/instance_redactor_spec.rb, spec/models/reindex_run_spec.rb, spec/models/work_spec.rb, spec/rails_admin/config/actions/redact_notice_spec.rb, spec/support/tasks.rb, spec/tasks/redact_and_reindex_works_spec.rb
**NO**
I have one more commit that's just linting that I'll push after your review.
1. auto-redacts work descriptions on work save
2. adds a rake task to let us go through all existing works to redact their descriptions
The rake task just does a thousand works at a time because reindexing all the things could be overwhelming. We'll put it in a cron job to slowly munch through the backlog.
We thought people wouldn't put sensitive information into work descriptions, but it turns out they do. We're going to suppress them from display. It turns out `description_original` is already suppressed from search, so once we redact `description`, this will keep sensitive info out of the search as well.
* make a work that contains a phone number, US social security number, or email address; save it; …
=> 15743 work redaction

app/controllers/application_controller.rb, spec/integration/user_authorizes_spec.rb, spec/support/sign_in.rb
**NO (Adam will need to test it first)**
Activates a redirection after user login to the pre-sign-in-screen page.
Go to `/pages/about`, click `Sign in` on the bottom, sign in, it should redirect you back to the `/pages/about` page.
- https://cyber.harvard.edu/projectmanagement/issues/15850
NO
NO
=> Redirect to pre-sign-in page after login

.rubocop.yml, Gemfile, Gemfile.lock, spec/integration/faceted_notice_search_spec.rb, spec/integration/fielded_notice_search_spec.rb, spec/integration/notice_search_spec.rb, spec/integration/redaction_spec.rb, spec/integration/reviewable_notice_spec.rb, spec/integration/submit_notice_via_web_spec.rb, spec/integration/user_submits_typed_notices_spec.rb, spec/integration/viewing_topics_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/curb_helpers.rb, spec/support/matchers/have_heading.rb, spec/support/matchers/have_words.rb, spec/support/page_objects/fielded_search_on_page.rb, spec/views/blog_entries/index.html.erb_spec.rb, spec/views/blog_entries/show.html.erb_spec.rb, spec/views/notices/new.html.erb_spec.rb, spec/views/notices/show.html.erb_spec.rb, spec/views/rails_admin/application/redact_notice.html.erb_spec.rb, spec/views/rails_admin/application/redact_queue.html.erb_spec.rb, spec/views/shared/_topic_list.html.erb_spec.rb
This requires some rewrites to the tests because Capybara3 handles
whitespace differently than Capybara2 did.
**YES**
Upgrades poltergeist and capybara in hopes of better test stability (they were pretty old versions).
There shouldn't be any - bundle install and then run tests as normal.
- https://cyber.harvard.edu/projectmanagement/issues/15903
NO
YES
=> Update capybara and poltergeist

.rubocop.yml, Gemfile, Gemfile.lock, app/views/pages/maintenance.html.erb, config/environment.rb, config/environments/production.rb, config/initializers/turnout.rb, doc/release.md, lib/tasks/lumen.rake, public/500.html
This requires upgrading rails_admin - there was a bug in 1.4.1 that
was making it impossible to modify middleware, thereby clashing with
turnout.
**YES**
I had removed the turnout gem because it made the test suite crash. Then I was sad that I wasn't able to put the site into maintenance mode when I deployed last night. Now I have figured out how to use turnout without making things crash.
`rake maintenance:start`, then visit any page on localhost. `rake maintenance:end` when you're tired of maintenance mode.
n/a
NO
YES
=> Add turnout back

app/assets/stylesheets/search/_index.scss, app/models/notice.rb, spec/integration/fielded_notice_search_spec.rb
**YES**
Adds a new sorting option to the notice search view called `Reported to Lumen` and updates the existing one called `Date`.
Use the search and test the sorting.
- https://cyber.harvard.edu/projectmanagement/issues/15495
NO
NO
=> Update sorting options in notice search view

app/helpers/notices_helper.rb, app/models/notice.rb, app/views/notices/search/_result.html.erb, spec/integration/fielded_notice_search_spec.rb
YES
Adds the `created_at` date field (labeled `Submitted to Lumen`) to the notice search result.
Try to search and check if every single result item has the `Submitted to Lumen` included.
- https://cyber.harvard.edu/projectmanagement/issues/15495
NO
NO
=> Add "Submitted to Lumen" date to notice search results

app/models/risk_assessment.rb, app/models/risk_trigger.rb, app/models/risk_trigger_condition.rb, config/initializers/rails_admin.rb, db/migrate/20190122150704_rename_risk_triggers.rb, db/migrate/20190122151538_create_new_risk_triggers.rb, db/schema.rb, db/seeds/risk_triggers.rb, spec/integration/reviewable_notice_spec.rb, spec/models/risk_assessment_spec.rb, spec/models/risk_trigger_condition_spec.rb, spec/models/risk_trigger_spec.rb
**YES**
Updates the risk triggers functionality. The current implementation is not complete and not useful.
Create a new risk trigger and risk trigger conditions. Assign the conditions to the trigger and try to add a new notice, properly configured it should make the notice as a risky one.
- https://cyber.harvard.edu/projectmanagement/issues/15785
YES 
NO
=> Fix risk triggers

app/serializers/notice_serializer.rb, app/views/notices/_works_urls.html.erb, spec/support/elasticsearch.rb, spec/views/notices/show.html.erb_spec.rb
**YES**
Communicates better when works don't have associated problematic URLs. (This should have been handled via model validations a long time ago, but it wasn't, and now it's very hard to back ourselves out of that situation.)
Disconnect all the infringing and/or copyrighted URLs from a work and then look at a page of a notice that references this work (or pull it from the API).
- https://cyber.harvard.edu/projectmanagement/issues/13176
NO
NO
=> Notify users when works were submitted without URLs

.gitignore, config/initializers/rack-attack.rb, config/initializers/whitelisted_ips.rb.example
We should be able to configure the safelist without having to redeploy
code.
**YES**
Lets us maintain a private list of IPs to whitelist.
Some legitimate researchers have been caught up in our DDOS prevention efforts, and we should be able to whitelist them as we get their IPs without needing to redeploy code.
Comment out the localhost whitelist, dramatically reduce the request limit, and hammer the server. Then add your localhost IP to the list (see config/initializers/whitelisted_ips.rb.example) and lo! access for you.
n/a
NO
NO
=> Make it easy to update researcher IP whitelist

app/assets/stylesheets/layouts/_application.scss, app/controllers/search_controller.rb, app/views/shared/_error.html.erb, spec/controllers/notices/search_controller_spec.rb
**NO**
Requires stakeholder approval; conversations in progress.
This prevents users from requesting search result pages past page 2000 (which just causes an elasticsearch error). It also prevents them from going too far into the search results unless they're authenticated or using the API, because it's computationally more intensive for us to serve those, and casual users are unlikely to page very far in.
Try visiting a search page with `page=10`, `page=11`, `page=11` while you are logged in, and `page=2001`.
Your localhost elasticsearch config may throw errors before page 2001, but production supports through 2000.
n/a
NO
NO
=> Prevent deep pagination

lib/tasks/lumen.rake
This should improve server performance, per the updated comment in the file.
**YES**
I'd like to push this out as a hotfix, actually.
See comment
It's fun to load test production via bot farm ddos!
A proper LRU cache, probably the standard Redis-backed rails option, would be better, but it would also be a lot more work.
Currently we're seeing spikes in various server metrics every 20 minutes. Post-deploy, those spikes should be smaller as there should be less content we need to regenerate.
n/a
NO
NO
=> Increase cache file time-to-live

app/helpers/notices_helper.rb, app/models/blog_entry.rb, app/models/relevant_question.rb, app/models/topic.rb, config/initializers/markdown.rb, spec/renders_markdown_spec.rb
There is also a Markdown constant defined within Redcarpet. They
clash; there can only be one. This results in continual irritated emails
from the server. Let's not.
**YES**
A few sentences describing the overall goals of the pull request's commits.
Why are we making these changes? Is there more work to be done to fully
achieve these goals?
YES | NO
YES | NO
=> Change name of Markdown parser

Gemfile, doc/release.md
**YES**
Stops us from loading bourbon in production. (It uses a lot of memory and we only need it for asset precompilation.)
our memory usage graphs
`derailed bundle:mem` with this branch and with dev show memory load differences, but the real proof will be post-deploy.
n/a
NO
NO
=> Don't load assets gems in prod

spec/integration/fielded_notice_search_spec.rb
**YES**
Skips our last intermittently failing test.
This isn't important enough to be worth debugging, and it's preventing us from being able to rely absolutely on our automated checks. Skipping this should mean that a failing test suite can be an absolute blocker to merge.
NO
NO
=> Skip intermittently failing test

app/views/rails_admin/main/_form_filtering_multiselect.html.haml, db/migrate/20190503161701_add_indices_to_notice.rb, db/schema.rb
**YES**
Speeds things up in two ways (title of the PR notwithstanding) --
One, by indexing some columns on Notice that we need to be indexed, according to our postgres slow query logs.
Two, by finding a place that railsadmin regularly performs ~70 second postgres queries (`SELECT COUNT(*) FROM "works"`) and just...not doing those.
Post-deployment, `/admin/notice/X/edit` should be hella faster. I'm not sure where the queries against Notice were being run so I'm not sure how to see the effect of these indexes.
- https://cyber.harvard.edu/projectmanagement/issues/16485
- https://cyber.harvard.edu/projectmanagement/issues/16422
YES
NO
=> 16485 index slow queries

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/views/shared/_footer.html.erb, config/initializers/rack-mini-profiler.rb, lib/tasks/lumen.rake, spec/rails_helper.rb, spec/views/shared/_footer.html.erb_spec.rb
**YES**
Adds rack-mini-profiler to all dev environments. Makes it visible in prod to super_admins. This will allow us to get much more detail on memory consumption in production, e.g. for fixing memory use problems in rails_admin. Because our elasticsearch and database situtions are so different in prod than in dev, there are certain things we can't metrize anywhere else.
omg the admin is so slow
Fire up `rails s` in dev and check out the cute little badge in the upper left. Click on it for all kinds of good data! Then try `RAILS_ENV=production rails s`; the badge will go away unless you're logged in as super_admin.
- https://cyber.harvard.edu/projectmanagement/issues/16481
NO
YES
=> 16481 profile memory in prod

.gitignore, doc/release.md, lib/tasks/lumen.rake
**YES**
Adds a cron job to fetch all recent file attachments of a certain type, to make it easier for one of our major users to do his research.
We ❤️ our researchers.
If you run the cron job, you'll end up with a `tar.gz` file and an `index.html` in `public/free_as_in_kittens`. You can then go to `/free_as_in_kittens/index.html` in your browser and download the file. Good times.
- https://cyber.harvard.edu/projectmanagement/issues/14122
NO
NO
=> Add cron job to aid user in his research

app/controllers/notices_controller.rb, config/application.rb, spec/controllers/notices_controller_spec.rb
**YES**
If in the API call to add a notice the authentication_token is missing, then an empty response is returned. After merger of this PR link of the API documentation would be given in response
- https://cyber.harvard.edu/projectmanagement/issues/14395
NO
NO
=> Give documentation link in response for missing auth token

Gemfile, Gemfile.lock
YES
The recaptcha gem doesn't expose responses from the recaptcha server, let's fix that. The forked and fixed gem is here https://github.com/berkmancenter/recaptcha.
We also need to set the `LOG_RECAPTCHA_RESPONSES` env variable to `true` to explicitly tell it to log.
https://cyber.harvard.edu/projectmanagement/issues/16537
~~- [ ] Stakeholder approval~~
NO
YES
=> Use monkeypatched recaptcha gem for debugging purposes

Gemfile, Gemfile.lock, app/controllers/token_urls_controller.rb, spec/controllers/token_urls_controller_spec.rb
YES
Fixes an issue with the full notice request view captcha being validated twice unintentionally.
https://cyber.harvard.edu/projectmanagement/issues/16537
NO
YES
=> 16537 fix full notice request validation

app/controllers/search_controller.rb, app/models/counternotice.rb, app/models/court_order.rb, app/models/data_protection.rb, app/models/date_range_filter.rb, app/models/defamation.rb, app/models/dmca.rb, app/models/entity.rb, app/models/entity_notice_role.rb, app/models/file_upload.rb, app/models/government_request.rb, app/models/law_enforcement_request.rb, app/models/notice.rb, app/models/other.rb, app/models/private_information.rb, app/models/searchability.rb, app/models/searches_models.rb, app/models/term_filter.rb, app/models/term_search.rb, app/models/trademark.rb, app/models/work.rb, app/views/shared/_navigation.html.erb
**YES**
Improves performance of search page.
Notice search is one of our most popular pages, and also one of our slowest. Skylight logs show that we're spending a lot of time fetching data from elasticsearch and/or the database. Looking at the code, `augment_instance` was hitting the db once for every search result, rather than fetching all the results from the db in one go. In addition, elasticsearch is pulling in complete records, when in fact we only use a handful of its data. This PR fixes those, and also applies a few other performance improvements noticed along the way.
In `rails c`, run something like
```
search_url = '/notices/search?term=batman&sort_by='
puts Benchmark.measure {
30.times do { app.get search_url }
}
```
Compare this branch and the dev branch. For me, on a …
=> 16533 augment instance perf

spec/controllers/original_notice_ids_controller_spec.rb, spec/integration/api_notice_search_spec.rb, spec/integration/faceted_notice_search_spec.rb, spec/integration/fielded_notice_search_spec.rb, spec/integration/generate_permanent_token_url_spec.rb, spec/integration/page_titles_spec.rb, spec/integration/reading_the_blog_spec.rb, spec/integration/submit_notice_via_api_spec.rb, spec/integration/viewing_topics_spec.rb, spec/support/elasticsearch.rb, spec/views/home/index.html.erb_spec.rb, spec/views/rails_admin/application/redact_queue.html.erb_spec.rb, spec/views/topics/show.html.erb_spec.rb
**YES**
This PR is to fix elasticsearch and rspec test suite. Rspec should start elasticsearch only for tests that are tagged after this PR is merged.
By running a test that is not tagged. This should not start elasticsearch.
Example : 
Run the spec/models/other_spec.rb tests on the dev branch. Elastic search server is started. Try running the same spec file on this branch, elasticsearch does not start. 
NO
NO
=> Config change to start elasticsearch only for required tests

lib/tasks/lumen.rake
**YES**
We have a cron job that periodically generates an archive of file attachments for one of our users, to aid in his research. However, the job sends him both original and supporting documents. This version only sends him supporting documents, while notifying him of the existence of original documents when redacted versions are not yet available.
Originals are as received by Lumen, and may contain sensitive information that needs to be redacted before the document can be publicly released. Notices may have no attachments; just original attachments; or original and supporting attachments (the supporting ones are generated after staff review of originals).
Make a new `CourtOrder`. Add an original and a supporting file to it. Set `USER_CRON_EMAIL` in `.env` to your email. Run `rake …
=> 16590 restrict cron files

config/initializers/rails_admin.rb, spec/integration/rails_admin_dashboard_spec.rb
Without the protocol-agnostic //, the url was being treated as a path
and appended onto the page's domain.
While we're at it, change the unhelpful "token url" link text to
something more specific.
**YES**
(see above)
Look at `/admin/token_url` on this branch vs the dev branch. (Make sure there is at least one token URL in your database.) Note that the link with the link text "Token url" on the dev branch is broken, whereas the corresponding link in this branch works.
n/a (conversation with Adam in slack)
NO
NO
=> Fix broken link in admin

config/initializers/rack-attack.rb, spec/config/initializers/rack-attack_spec.rb, spec/spec_helper.rb
**YES**
We have been rate-limiting logged-in users who are using the web interface, even when their level of  permissions would allow unthrottled API access. We should not do this. This PR adds a new whitelist for authenticated users with suitable permissions.
They may still be throttled at the proxy, which cannot tell that they are logged in. However, if they're working at normal human speeds, that is unlikely to be a problem.
Log in as a researcher and issue a bunch of manual requests against dev; you'll get the 429. Do the same against this branch and you should not see 429. (You may need to clear the cache between runs, and you'll need to temporarily comment out the localhost whitelist if you're making requests against localhost.)
- …
=> 16691 rate limiting but too much

lib/tasks/lumen.rake, spec/tasks/redact_and_reindex_works_spec.rb
We still get the occasional warning about filenames with special
characters not being handled correctly by the cron job.
**YES**
(see above)
n/a
NO
NO
=> Remove additional special characters from report

app/helpers/application_helper.rb, spec/integration/viewing_notices.spec.rb
**YES**
Makes it possible to set a list of notices in the `.env` file that will be default show the full notice view.
https://cyber.harvard.edu/projectmanagement/issues/16884
NO
NO
=> Make it possible to whitelist notices and show their full version

spec/integration/page_titles_spec.rb, spec/integration/reading_the_blog_spec.rb, spec/views/shared/_navigation.html.erb_spec.rb
91b25eaf8 removed the blog link from the navigation bar, which means
that tests which mandate visiting / and clicking on 'Blog' no longer
work. These tests are removed or updated.
**YES**
(see above)
`rspec` should succeed, whereas it fails on dev.
n/a
NO
NO
=> Update failing blog tests

app/helpers/comfy/comfy_helper.rb, app/views/blog_entries/_comfy_entry.html.erb, app/views/cms_pages/_layout.html.erb, config/environments/production.rb, lib/tasks/lumen.rake, spec/lib/tasks/blog_import_to_cms_spec.rb, spec/lib/tasks/migrate_original_news_ids_to_cms_spec.rb
**YES**
Adds a rails task to migrate the permalinks for original_notice_ids -- we need to migrate that content before we can rip it out in the final CMS deploy.
cool URIs don't change
Run the task. At that point, for every `/original_news_id/X` to `/blog_entries/Y` redirect, there should also be a `/cms/original_news_id/X` to `/cms/blog_entries/Y` redirect
- https://cyber.harvard.edu/projectmanagement/issues/17078
- ~[ ] Stakeholder approval~
NO
NO
=> Migrate cms content

app/models/notice_builder.rb, lib/validates_urls.rb, spec/models/infringing_url_spec.rb
**YES**
One of our submitters was having 500 errors submitting notices. This seems to be linked to differences in data representation between JSON data and multipart form data (the latter is what they were submitting). I've gotten around this by converting everything to JSON format early in the process and verified that it works on production with an example failed submission that they shared with us.
Unfortunately, the failed submission *worked on localhost and a test server* even with the prior, failing-on-production, code. This means I was unable to use it to generate a test that failed before the fix, so I don't have a programmatic way to verify the fix, or guard against breaking it in future. Nor do I know what element in the stack on production might have been causing this …
=> 17179 form data bug

app/controllers/redirecting_controller.rb, spec/support/shared_examples/redirecting_controller_for.rb
**YES**
When someone accesses a submission_id or original_notice_id page and we don't find a notice with that submission_id or original_notice_id, but there IS a notice with that id, we redirect to its page. This is in addition to the existing behavior of handling submission_ids or original_notice_ids when they do exist, and 404ing if we can't find anything (having tested both the given type of ID and the regular id).
We think outside parties' scripts are interpolating new notice ID
numbers into old format URLs, leading to 404s where users expect data.
We don't have enough log/customer information to be certain, but if we
try this and stop getting these complaints we were right; if we start
getting a different kind of complaints ("I clicked the URL and got
something irrelevant!") we were …
=> Fallback to /notices/X when /submission_id/X not found

Gemfile.lock, app/models/work.rb, spec/integration/submit_notice_via_api_spec.rb
**YES**
The work to fix concatenated URLs caused us to reject URLs of the form `http://httpweb.whatever.com`.
Compare submitting the above example URL on this branch and on dev.
- https://cyber.harvard.edu/projectmanagement/issues/17279
NO
YES
=> 17279 malformed url edge case

app/helpers/notices_helper.rb
**YES**
Fixes an issue with caching wrong notice attachment urls (with a missing access token).
https://cyber.harvard.edu/projectmanagement/issues/17288
NO
NO
=> Cache notice attachment urls per access token to avoid wrong links

app/views/notices/select_type.html.erb, spec/integration/submit_notice_via_web_spec.rb
This has worked for a while, but it wasn't offered on /notices/new --
since Counternotice is not a subtype of Notice it isn't caught in the
Notice.type_models net.
**YES**
Adds Counternotice to the list of options at /notices/new, so that people are actually able to find the feature.
- https://cyber.harvard.edu/projectmanagement/issues/17283
NO
NO
=> Expose Counternotice creation functionality

CHANGELOG.md, app/helpers/notices_helper.rb, app/models/notice.rb, app/models/placeholder.rb, app/models/reindex_run.rb, app/serializers/notice_serializer.rb, app/views/notices/_placeholder_show.html.erb, app/views/notices/select_type.html.erb, app/views/notices/show.html.erb, spec/factories.rb, spec/integration/api_notice_search_spec.rb, spec/views/notices/new.html.erb_spec.rb, spec/views/notices/select_type.html.erb_spec.rb
**YES**
Adds a Placeholder notice type.
Sometimes notice providers want to be able to link to a generic notice, representing a class of notices they receive in large numbers, whose specifics are not relevant and/or shareable.
- https://cyber.harvard.edu/projectmanagement/issues/16186
NO
NO
=> 16186 placeholders

lib/tasks/lumen.rake
**YES**
Creates a new rake task that reindexes entities in ES created or updated after a specific date in the past.
This will help to catchup after migrating to a newer ES version.
https://cyber.harvard.edu/projectmanagement/issues/17201
NO
NO
=> Add indexing catchup rake task

app/assets/stylesheets/notices/_forms.scss, app/helpers/notices_helper.rb, app/views/notices/form_components/_roles.html.erb, spec/integration/submit_notice_via_web_spec.rb
**YES**
Adds default data to submitter and recipient fields on the web form, when the user is connected to an entity.
It's annoing for users to have to hand-enter the same data repeatedly, and it leads to many near-duplicate entities in our db.
Go to the create notices web form as a logged-in user with submitter privileges. If you have an associated entity, you will see that the submitter and recipient forms are prefilled.
- https://cyber.harvard.edu/projectmanagement/issues/17341
NO
NO
=> 17341 default fields

app/serializers/notice_serializer.rb, spec/controllers/notices_controller_spec.rb
If they've been redacted, we don't want to share them.
**YES**
Removes `url_original` from serializers so we don't send potentiall redacted information via the API.
Send API requests or .json-formatted GET requests against this and dev, compare data.
- https://cyber.harvard.edu/projectmanagement/issues/17356
NO
NO
=> Don't send original URLs via API

app/helpers/notices_helper.rb, app/views/notices/_works_urls.html.erb, spec/integration/viewing_notices.spec.rb
Safelisted notices don't have any more content because they're already
showing all content -- this doesn't require a change to our existing
logic, but this PR adds a test to verify.
Confidential court orders shouldn't offer more access because there
isn't anything else to access.
There are potentially enough edge cases in the business logic here
that I've extracted it to a helper method to make it easier to change.
**YES**
See above.
- https://cyber.harvard.edu/projectmanagement/issues/17383
NO
NO
=> Don't offer more notice content when there isn't any

app/helpers/notices_helper.rb, app/views/entities/_address.html.erb, app/views/entities/_entity.html.erb, app/views/entities/_recipient.html.erb, app/views/entities/_sender.html.erb, app/views/notices/show.html.erb, spec/integration/viewing_notices.spec.rb
...that was the scope of the ticket, anyway. This ends up refactoring
the entity template because the conditionals were tangled enough that
it was hard to tell why the date wasn't displaying. It's now been
separated into its constituent parts, with some cruft removed.
While we're at it, fixed the bug that made empty addresses display as
",,,".
**YES**
Above.
Go to a notice whose sender is redacted (that is, has hide_entities set to true on the notice); you will see the date_sent.
Go to a notice whose sender or recipient does not have an address; you will NOT see ",,," on the address line.
- https://cyber.harvard.edu/projectmanagement/issues/16003
NO
NO
=> Make sure date_sent shows when sender is redacted

Gemfile, Gemfile.lock, README.md, spec/integration/submit_token_url_spec.rb, spec/rails_helper.rb, spec/support/capybara.rb, spec/support/notice_actions.rb
phantomjs development ceased in 2018, and it's increasingly hard to
integrate with CI.
**YES**
Rips out phantomjs, uses headless chrome instead. Correspondingly rips out poltergeist, uses selenium.
I'm trying to migrate from travis (which is broken) to circle, and standing up phantomjs on circle is a pain.
n/a
n/a
- ~~[ ] Tests~~ (existing tests still pass; no feature changes -> no new tests)
NO
YES
=> Replace phantomjs with selenium
